In [7]:
import numpy as np
list = (1,2,3,4)
array = np.array(list)
print(array)

[1 2 3 4]


In [18]:
array = np.random.rand(4)
zero = np.zeros(4)
print(zero)
print(array)

[0. 0. 0. 0.]
[0.83509511 0.92643815 0.81357186 0.82541262]


In [32]:
array = np.array([[1,2,3,4],[4,5,6,7]])
print(array)
print(array.shape)
array3 = np.array([[[1,2,3,4],[1,2,3,4],[4,5,6,7]]])
print(array3.ndim)

[[1 2 3 4]
 [4 5 6 7]]
(2, 4)
3


In [36]:
print(array3[0][0][0])
print(array3[0][0][-1])

1
4


In [44]:
array1 = np.array([[1,2,3,4],[4,5,6,7]])
array2 = np.array([[1,2,3,4],[4,4,4,5]])
np.concatenate([array1,array2])
print(np.vstack([array1,array2]))

[[1 2 3 4]
 [4 5 6 7]
 [1 2 3 4]
 [4 4 4 5]]


In [41]:
print(array1[0,:2])

[1 2]


In [42]:
print(array1[:,1])

[2 5]


In [48]:
a = np.array([1,2,3,4] , dtype = 'float64')
print(a)

[1. 2. 3. 4.]
